
# Classes

class MyApi
  include HTTParty
  attr_accessor default_headers: bot

  def initialize: -> void


  def get_access_token(Hash[String, untyped] body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def add_account({external_id: String, business_information: , industry: , addresses: Array[Object], email: String, phone_number: String} body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def get_account(String id, ?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def update_account({external_id: String, business_information: , industry: , addresses: Array[Object], email: String, phone_number: String} body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def deprecated_add_contact({account_id: String, relationship: String, first_name: String, last_name: String, email: String, communications_opt_out: String, contact_numbers: Array[Object]} body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def deprecated_update_contact({account_id: String, relationship: String, first_name: String, last_name: String, email: String, communications_opt_out: String, contact_numbers: Array[Object]} body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def set_servicing({owner_username: String, advisor_username: String, business_unit: String, branch: String, segment: String} body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def add_policy({id: String, external_id: String, policy_number: String, account_id: String, status: String, effective_date: String, expiration_date: String, cancellation_date: String, premium: , taxes: , fees: , insurance_type: String, purchase_type: String, renewal_flow: String, billing_carrier_id: String, issuing_carrier_id: String, finance_contract_number: String, intermediary_id: String} body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def policies(?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def get_policy(String id, ?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def policies_id_endorsements({id: String, policy_id: String, account_id: String, status: String, endorsement_number: String, type_of_change: String, processed_date: String, description: String, effective_date: String, premium_change: , taxes_change: , fees_change: , financed_amount: , correction_of_endorsement_id: String} body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def policies_id_endorsements(String id, ?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def policies_id_payments(String id, ?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def add_certificate({type: String, policy_ids: Array[String], fields: } body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def carriers(?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def insurance_types(?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def intermediaries(?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def add_subscription({endpoint: String, events: Array[String], notify_on_error_email: String} body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def list_subscriptions(?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def rotate_signing_key(Hash[String, untyped] body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def update_subscription({endpoint: String, events: Array[String], notify_on_error_email: String} body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def delete_subscription(Hash[String, untyped] body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def add_payment_method({type: String, provider: String, token: String, account_id: String} body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def quotes(?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def get_quote(String id, ?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def update_quote({account_id: String, insurance_type: String, policy_ids: Array[String], name: String, stage: String, premium: , taxes: , fees: , effective_date: String, expiration_date: String} body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def endorsements({id: String, policy_id: String, account_id: String, status: String, endorsement_number: String, type_of_change: String, processed_date: String, description: String, effective_date: String, premium_change: , taxes_change: , fees_change: , financed_amount: , correction_of_endorsement_id: String} body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def endorsements_id_(String id, ?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def endorsements_id_commissions(String id, ?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def endorsements_id_payments(String id, ?Hash[String, String] params, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def add_contact({account_id: String, relationship: String, first_name: String, last_name: String, email: String, communications_opt_out: String, contact_numbers: Array[Object]} body, ?Hash[untyped, untyped] options) -> HTTParty::Response

  def update_contact({account_id: String, relationship: String, first_name: String, last_name: String, email: String, communications_opt_out: String, contact_numbers: Array[Object]} body, ?Hash[untyped, untyped] options) -> HTTParty::Response
end
